### ISSUE TITLE
Hi there, does Bagua support model parallel across different nodes? If so, would you mind providing a simple example in examples folder? Thank you.

### ISSUE THREAD

**Issue by elricwan** [BaguaSys/bagua#136]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NOBLES5E** [comment]
Currently Bagua by itself does not support model parallel. It is on our roadmap though.

At the moment, you can use PyTorch's [rpc](https://pytorch.org/tutorials/intermediate/rpc_tutorial.html#distributed-rnn-using-distributed-autograd-and-distributed-optimizer) to do distributed model parallelism. Also, if your model uses both data parallel and model parallel, you can still use Bagua to accelerate the data parallel part.
