### ISSUE TITLE
 Elastic Training support for previous version of pytorch

### ISSUE THREAD

**Issue by Tengxu-Sun** [BaguaSys/bagua#142]
Now the  Elastic Training needs the version of pytorch >= 1.9.0. However, there are some situations where torch version is previous than that. So can we consider this function adapting to the previous version of pytorch?

**Comment by NOBLES5E** [comment]
@shjwudp Let's also add old torchelastic launcher in `bagua/distributed`.

**Comment by shjwudp** [comment]
> @shjwudp Let's also add old torchelastic launcher in `bagua/distributed`.

Maybe we can try to upgrade pytorch first, let's discuss it first @Tengxu-Sun

**Comment by shjwudp** [comment]
pytorch upgrade is possible, the issue is closed.
