### ISSUE TITLE
Support Bagua in PyTorch Lightning

### ISSUE THREAD

**Issue by NOBLES5E** [BaguaSys/bagua#304]

**Comment by tchaton** [comment]
Dear @NOBLES5E,

I am part of PyTorch Lightning. This framework looks amazing. 
We have some overlapping features but I wondered if you would be interested to work with us to upstream some of those features to Lightning directly.

Feel free to join Lightning Slack and ping me directly with tchaton username.

Best,
T.C

**Comment by NOBLES5E** [comment]
Cool. I will reach you on slack.
