### ISSUE TITLE
errors with DecentralizedAlgorithm in shift_one mode

### ISSUE THREAD

**Issue by ProHuper** [BaguaSys/bagua#380]
I used DecentralizedAlgorithm in shift_one peer_selection_mode with 8 GPUs, bagua backend says i have odd number ranks (only one), but you can see from the NCCL log that this job does have 8 GPUs. Does n_ranks here mean node number or gpu number exactly？

![image](https://user-images.githubusercontent.com/21972658/142022471-161d3c00-1096-47d6-ac05-8b858e9e94ed.png)

**Comment by wangraying** [comment]
`nranks` means the number of ranks in the NCCL communicator. 

Decentralized algorithm will enable hierarchical reduce by default, which means only inter-node decentralized communication will be performed, with an intra-node allreduce before it and an intra-node bcast after it. To try it out on 8 GPUs, set `hierarchical =False`.  See [API](https://bagua.readthedocs.io/en/latest/autoapi/bagua/torch_api/algorithms/decentralized/index.html) for details.

**Comment by ProHuper** [comment]
got it!
