### ISSUE TITLE
turn off buagua-net

### ISSUE THREAD

**Issue by CaRRotOne** [BaguaSys/bagua#546]
Hi, I want to know if I could turn off bagua-net in this [script](https://github.com/BaguaSys/bagua/blob/master/examples/benchmark/synthetic_benchmark.py).  so that I could compare with the original pytorch throughput . passing the --enable_bagua_net argument in bagua.distributed.launch does not work.

**Comment by NOBLES5E** [comment]
By default bagua-net is not enabled: https://github.com/BaguaSys/bagua/blob/master/bagua/distributed/run.py#L394

**Comment by CaRRotOne** [comment]
> By default bagua-net is not enabled: https://github.com/BaguaSys/bagua/blob/master/bagua/distributed/run.py#L394
I did a test, the throughput is same Whether or not to pass the --enable_bagua_net argument .
![image](https://user-images.githubusercontent.com/2860023/156483233-caabf235-338e-4628-abba-a782c731b309.png)
![image](https://user-images.githubusercontent.com/2860023/156483274-cc5fb4c7-1fc8-4325-8aec-bed262438642.png)

**Comment by NOBLES5E** [comment]
Try following https://tutorials.baguasys.com/faq_troubleshooting#nccl-warn-reduce-invalid-reduction-operation-4 to install dependencies and run with `NCCL_DEBUG=info` to see if the bagua net libnccl-net plugin is correctly found (the actual library should be in `~/.data/bagua-net/libnccl-net.so`).

Keep in mind that benchmarks are highly dependent on many factors including the workload and environment. It seems that in your screenshot you are running the workload on a single machine, where it is expected that bagua-net shows no benefit (on a single machine nccl will use shared memory/nvlink directly, while bagua-net optimizes nccl TCP performance).

**Comment by CaRRotOne** [comment]
@NOBLES5E thanks for your remind. so bagua-net only optimizes nccl TCP permormance. As for RDMA, would you do some performance optimization in the feature?

**Comment by NOBLES5E** [comment]
There's no transport level optimization for RDMA supported yet.

**Comment by NOBLES5E** [comment]
The same question was answered in https://github.com/google/nccl-fastsocket/issues/2

It seems that your 10Gbps NIC is already saturated. In this case, the compression algorithms in bagua (for example https://tutorials.baguasys.com/algorithms/bytegrad) may help you better.

**Comment by luoguohao** [comment]
@

> The same question was answered in [google/nccl-fastsocket#2](https://github.com/google/nccl-fastsocket/issues/2)
> 
> It seems that your 10Gbps NIC is already saturated. In this case, the compression algorithms in bagua (for example https://tutorials.baguasys.com/algorithms/bytegrad) may help you better.
oh， i just forgot comparing to  the nic max bandwidth, i will using higher bandwidth nic to rerun the tests. thx
