### ISSUE TITLE
where the code related to communication and calculation of overlap of one algorithm？

### ISSUE THREAD

**Issue by chst1994** [BaguaSys/bagua#662]
I didn't find code related to communication and calculation of overlap，can you show me an example?  Thanks！

**Comment by wangraying** [comment]
The overlapping mechanism is implemented in [backward hook](https://github.com/BaguaSys/bagua/blob/a71c904b10e141c1d5ab5675f86c96bdada9f1ea/bagua/torch_api/data_parallel/bagua_distributed.py#L417). During the backward process, when tensors in a bucket are ready, a background thread (implemented in rust) will start communication (performing comm op on the bucket), while the main thread can continue the backward process. In this way, successive buckets' communication and computation can overlap together.
